services:
  worker:
    build:
      context: .
    environment:
      HEROKU_DEPLOYMENT: dokploy
      HEROKU_NO_GIT: "1"
      HEROKU_DATA_ROOT: /data/heroku
    volumes:
      - worker:/data/heroku
    restart: unless-stopped
    ports:
      - "${PORT:-8080}:8080"

volumes:
  worker:
